#!/usr/bin/env bash
set -euo pipefail

for arg in "$@"; do
  case "$arg" in
	--model=*) model="${arg#*=}" ;;
	--interim-results=*) interim_results="${arg#*=}" ;;
	--smart-format=*) smart_format="${arg#*=}" ;;
	--punctuate=*) punctuate="${arg#*=}" ;;
	--language=*) language="${arg#*=}" ;;
	--diarize=*) diarize="${arg#*=}" ;;
	--oneshot) oneshot=true ;;
	--*) echo >&2 "Unknown option: $arg"; exit 1 ;;
	*) echo >&2 "Unknown argument: $arg"; exit 1 ;;
  esac
done

params="model=${model:-nova-2-general}"
params="$params&interim_results=${interim_results:-false}"
params="$params&smart_format=${smart_format:-false}"
params="$params&punctuate=${punctuate:-false}"
params="$params&diarize=${diarize:-false}"
params="$params&language=${language:-en}"
url="wss://api.deepgram.com/v1/listen?$params"
auth="Authorization: Token ${DEEPGRAM_API_KEY}"

coproc WEBSOCAT { 
  websocat -E --no-close -H "$auth" --binary --no-line - msg2line:"$url"
}

exec {WEBSOCAT_IN}<&${WEBSOCAT[1]}
exec {WEBSOCAT_OUT}<&${WEBSOCAT[0]}

miniogg ~/minirec.sock >&$WEBSOCAT_IN & MINIOGG_PID=$!

if [ -n "${oneshot:-}" ]; then
  read -r line <&$WEBSOCAT_OUT
  echo "$line" | jq -r '.channel.alternatives[0].transcript'
  exec {WEBSOCAT_IN}<&-
  exec {WEBSOCAT_OUT}<&-
  kill -SIGINT $MINIOGG_PID  
  kill -SIGINT $WEBSOCAT_PID
else
  while read -r line; do
    echo "$line"
  done <&$WEBSOCAT_OUT
fi
