name: build minirec and miniogg

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:bigbluebutton/support
        sudo apt-get update
        sudo apt-get install -y pkg-config libopusenc-dev
    - name: make
      run: make
    - name: tarball
      run: |
         tar cvf minirec-$(uname -s)-$(uname -m).tar.gz minirec miniogg minigram talk-mode.el
    - name: upload
      uses: actions/upload-artifact@v3
      with:
	name: minirec-Linux-x86_64
	path: minirec-Linux-x86_64.tar.gz
      
